package com.block154.courierpilot

import android.content.Context
import android.os.Build
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.util.UUID
import java.util.concurrent.Executors
import java.util.concurrent.ScheduledFuture
import java.util.concurrent.TimeUnit

internal data class RemoteDiagnosticsStatus(
    val enabled: Boolean,
    val queued: Int,
    val lastUploadAt: Long,
    val lastError: String,
)

/**
 * Opt-in, privacy-safe remote diagnostics for CourierPilot development.
 *
 * CaptureEventLog never performs network/disk queue work on the notification/accessibility caller
 * thread. Events are handed to a dedicated single background thread, persisted to a small queue,
 * then uploaded in batches. Failed uploads remain queued and are retried with bounded backoff.
 *
 * No screenshots, OCR frames, addresses, customer text, GPS coordinates or Android identifiers are
 * uploaded. The installation id below is a random CourierPilot-local UUID generated by this app.
 */
internal object RemoteDiagnostics {
    private const val ENDPOINT = "https://wolt-api.zivkr.pp.ua/courierpilot/v1/events"
    private const val SETTINGS_PREFS = "courierpilot_remote_diagnostics"
    private const val QUEUE_PREFS = "courierpilot_remote_diagnostics_queue"
    private const val KEY_ENABLED = "enabled"
    private const val KEY_INSTALL_ID = "install_id"
    private const val KEY_QUEUE = "queue"
    private const val KEY_LAST_UPLOAD = "last_upload"
    private const val KEY_LAST_ERROR = "last_error"
    private const val MAX_QUEUE = 400
    private const val BATCH_SIZE = 60
    private const val INITIAL_FLUSH_DELAY_MS = 4_000L
    private const val MAX_RETRY_DELAY_MS = 15L * 60L * 1000L

    private val processSessionId = UUID.randomUUID().toString()
    private val executor = Executors.newSingleThreadScheduledExecutor { runnable ->
        Thread(runnable, "CourierPilotRemoteDiag").apply { isDaemon = true }
    }
    private var scheduledFlush: ScheduledFuture<*>? = null
    private var retryDelayMs = 30_000L

    fun enabled(context: Context): Boolean =
        context.getSharedPreferences(SETTINGS_PREFS, Context.MODE_PRIVATE)
            .getBoolean(KEY_ENABLED, false)

    fun setEnabled(context: Context, enabled: Boolean) {
        val app = context.applicationContext
        app.getSharedPreferences(SETTINGS_PREFS, Context.MODE_PRIVATE)
            .edit()
            .putBoolean(KEY_ENABLED, enabled)
            .apply()
        if (enabled) {
            resume(app)
        } else {
            executor.execute {
                app.getSharedPreferences(QUEUE_PREFS, Context.MODE_PRIVATE).edit().remove(KEY_QUEUE).apply()
                scheduledFlush?.cancel(false)
                scheduledFlush = null
                retryDelayMs = 30_000L
            }
        }
    }

    fun status(context: Context): RemoteDiagnosticsStatus {
        val settings = context.getSharedPreferences(SETTINGS_PREFS, Context.MODE_PRIVATE)
        val queueRaw = context.getSharedPreferences(QUEUE_PREFS, Context.MODE_PRIVATE)
            .getString(KEY_QUEUE, null)
        return RemoteDiagnosticsStatus(
            enabled = settings.getBoolean(KEY_ENABLED, false),
            queued = readArray(queueRaw).length(),
            lastUploadAt = settings.getLong(KEY_LAST_UPLOAD, 0L),
            lastError = settings.getString(KEY_LAST_ERROR, "").orEmpty(),
        )
    }

    /** Called from Application startup; it only schedules background work when the user opted in. */
    fun resume(context: Context) {
        val app = context.applicationContext
        if (!enabled(app)) return
        executor.execute {
            if (queueSize(app) > 0) scheduleFlushOnExecutor(app, INITIAL_FLUSH_DELAY_MS)
        }
    }

    /**
     * Caller-safe entry point. It returns immediately after handing the event to our executor.
     */
    fun enqueue(context: Context, event: CaptureEvent) {
        val app = context.applicationContext
        if (!enabled(app)) return
        if (event.stage.startsWith("remote_diag")) return
        executor.execute {
            persistEvent(app, event)
            scheduleFlushOnExecutor(app, INITIAL_FLUSH_DELAY_MS)
        }
    }

    private fun persistEvent(context: Context, event: CaptureEvent) {
        if (!enabled(context)) return
        val prefs = context.getSharedPreferences(QUEUE_PREFS, Context.MODE_PRIVATE)
        val queue = readArray(prefs.getString(KEY_QUEUE, null))
        queue.put(
            JSONObject()
                .put("id", UUID.randomUUID().toString())
                .put("session", processSessionId)
                .put("timestamp", event.timestamp)
                .put("stage", event.stage.take(48))
                .put("platform", event.platform.take(24))
                .put("message", RemoteDiagnosticsPrivacy.sanitize(event.stage, event.message))
        )
        val trimmed = JSONArray()
        val start = (queue.length() - MAX_QUEUE).coerceAtLeast(0)
        for (i in start until queue.length()) {
            queue.optJSONObject(i)?.let(trimmed::put)
        }
        prefs.edit().putString(KEY_QUEUE, trimmed.toString()).apply()
    }

    private fun scheduleFlushOnExecutor(context: Context, delayMs: Long) {
        if (!enabled(context)) return
        if (scheduledFlush?.isDone == false) return
        scheduledFlush = executor.schedule({
            scheduledFlush = null
            flushOneBatch(context)
        }, delayMs, TimeUnit.MILLISECONDS)
    }

    private fun flushOneBatch(context: Context) {
        if (!enabled(context)) return
        val batch = peekBatch(context) ?: return
        when (val outcome = uploadBatch(context, batch)) {
            is UploadOutcome.Success -> {
                removeEvents(context, batch.ids)
                markUploadSuccess(context)
                retryDelayMs = 30_000L
                if (queueSize(context) > 0) scheduleFlushOnExecutor(context, 500L)
            }
            is UploadOutcome.Drop -> {
                removeEvents(context, batch.ids)
                markUploadError(context, outcome.reason)
                retryDelayMs = 30_000L
                if (queueSize(context) > 0) scheduleFlushOnExecutor(context, 1_000L)
            }
            is UploadOutcome.Retry -> {
                markUploadError(context, outcome.reason)
                val delay = retryDelayMs
                retryDelayMs = (retryDelayMs * 2L).coerceAtMost(MAX_RETRY_DELAY_MS)
                scheduleFlushOnExecutor(context, delay)
            }
        }
    }

    private data class PendingBatch(
        val sessionId: String,
        val ids: Set<String>,
        val events: JSONArray,
    )

    private fun peekBatch(context: Context): PendingBatch? {
        val prefs = context.getSharedPreferences(QUEUE_PREFS, Context.MODE_PRIVATE)
        val queue = readArray(prefs.getString(KEY_QUEUE, null))
        if (queue.length() == 0) return null
        val firstSession = queue.optJSONObject(0)?.optString("session").orEmpty()
        if (firstSession.isBlank()) return null

        val out = JSONArray()
        val ids = linkedSetOf<String>()
        for (i in 0 until queue.length()) {
            if (out.length() >= BATCH_SIZE) break
            val item = queue.optJSONObject(i) ?: continue
            if (item.optString("session") != firstSession) break
            val id = item.optString("id")
            if (id.isBlank()) continue
            ids += id
            out.put(
                JSONObject()
                    .put("id", id)
                    .put("timestamp", item.optLong("timestamp"))
                    .put("stage", item.optString("stage"))
                    .put("platform", item.optString("platform"))
                    .put("message", item.optString("message"))
            )
        }
        if (out.length() == 0) return null
        return PendingBatch(firstSession, ids, out)
    }

    private sealed interface UploadOutcome {
        data object Success : UploadOutcome
        data class Retry(val reason: String) : UploadOutcome
        data class Drop(val reason: String) : UploadOutcome
    }

    private fun uploadBatch(context: Context, batch: PendingBatch): UploadOutcome {
        val payload = JSONObject()
            .put("schema", 1)
            .put("install_id", installId(context))
            .put("session_id", batch.sessionId)
            .put("app_version", BuildConfig.VERSION_NAME)
            .put("version_code", BuildConfig.VERSION_CODE)
            .put("android_sdk", Build.VERSION.SDK_INT)
            .put("device_model", "${Build.MANUFACTURER} ${Build.MODEL}".take(80))
            .put("events", batch.events)
            .toString()
            .toByteArray(Charsets.UTF_8)

        var connection: HttpURLConnection? = null
        return try {
            connection = (URL(ENDPOINT).openConnection() as HttpURLConnection).apply {
                requestMethod = "POST"
                connectTimeout = 8_000
                readTimeout = 8_000
                doOutput = true
                useCaches = false
                setRequestProperty("Content-Type", "application/json; charset=utf-8")
                setRequestProperty("User-Agent", "CourierPilot/${BuildConfig.VERSION_NAME}")
                setFixedLengthStreamingMode(payload.size)
            }
            connection.outputStream.use { it.write(payload) }
            val code = connection.responseCode
            when {
                code in 200..299 -> {
                    connection.inputStream?.use { it.readBytes() }
                    UploadOutcome.Success
                }
                code == 408 || code == 425 || code == 429 || code >= 500 -> {
                    connection.errorStream?.close()
                    UploadOutcome.Retry("HTTP $code")
                }
                else -> {
                    connection.errorStream?.close()
                    // A permanent client/schema error must not poison the queue forever.
                    UploadOutcome.Drop("HTTP $code")
                }
            }
        } catch (t: Throwable) {
            UploadOutcome.Retry(t.javaClass.simpleName)
        } finally {
            connection?.disconnect()
        }
    }

    private fun installId(context: Context): String {
        val prefs = context.getSharedPreferences(SETTINGS_PREFS, Context.MODE_PRIVATE)
        val existing = prefs.getString(KEY_INSTALL_ID, null)
        if (!existing.isNullOrBlank()) return existing
        val generated = UUID.randomUUID().toString()
        prefs.edit().putString(KEY_INSTALL_ID, generated).apply()
        return generated
    }

    private fun removeEvents(context: Context, ids: Set<String>) {
        if (ids.isEmpty()) return
        val prefs = context.getSharedPreferences(QUEUE_PREFS, Context.MODE_PRIVATE)
        val queue = readArray(prefs.getString(KEY_QUEUE, null))
        val remaining = JSONArray()
        for (i in 0 until queue.length()) {
            val item = queue.optJSONObject(i) ?: continue
            if (item.optString("id") !in ids) remaining.put(item)
        }
        prefs.edit().putString(KEY_QUEUE, remaining.toString()).apply()
    }

    private fun queueSize(context: Context): Int =
        readArray(
            context.getSharedPreferences(QUEUE_PREFS, Context.MODE_PRIVATE)
                .getString(KEY_QUEUE, null)
        ).length()

    private fun markUploadSuccess(context: Context) {
        context.getSharedPreferences(SETTINGS_PREFS, Context.MODE_PRIVATE).edit()
            .putLong(KEY_LAST_UPLOAD, System.currentTimeMillis())
            .putString(KEY_LAST_ERROR, "")
            .apply()
    }

    private fun markUploadError(context: Context, error: String) {
        context.getSharedPreferences(SETTINGS_PREFS, Context.MODE_PRIVATE).edit()
            .putString(KEY_LAST_ERROR, error.take(120))
            .apply()
    }

    private fun readArray(raw: String?): JSONArray = try {
        if (raw.isNullOrBlank()) JSONArray() else JSONArray(raw)
    } catch (_: Throwable) {
        JSONArray()
    }
}

internal object RemoteDiagnosticsPrivacy {
    private val emailRegex = Regex("(?i)\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b")
    private val phoneRegex = Regex("(?<!\\d)\\+?\\d[\\d ()-]{7,}\\d")
    private val coordinatesRegex = Regex("-?\\d{1,3}\\.\\d{4,}\\s*[,/]\\s*-?\\d{1,3}\\.\\d{4,}")
    private val notificationTextRegex = Regex("(?is)(;\\s*text=).*$")

    fun sanitize(stage: String, raw: String): String {
        if (stage.startsWith("gps_", ignoreCase = true) ||
            stage.startsWith("address_", ignoreCase = true)
        ) {
            return "details redacted"
        }
        return raw
            .replace(notificationTextRegex, "$1[redacted]")
            .replace(emailRegex, "[email]")
            .replace(phoneRegex, "[phone]")
            .replace(coordinatesRegex, "[coords]")
            .replace('\n', ' ')
            .replace('\r', ' ')
            .take(320)
    }
}
